import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header";

const index = () => {
  return (
    <>
      <Head>
        <title>New App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-orange-500">
        <Header />
      </main>
    </>
  );
};

export default index;
